/* automatically generated by rust-bindgen 0.72.1 */

pub const METASK_AGENTCORE_ABI_V1: u32 = 1;
pub const METASK_AGENTCORE_ABI_REVISION: u32 = 5;
pub const METASK_AGENTCORE_STATUS_OK: u32 = 0;
pub const METASK_AGENTCORE_STATUS_INVALID_ARGUMENT: u32 = 1;
pub const METASK_AGENTCORE_STATUS_OUT_OF_MEMORY: u32 = 2;
pub const METASK_AGENTCORE_STATUS_BUSY: u32 = 3;
pub const METASK_AGENTCORE_STATUS_STALE_RUN: u32 = 4;
pub const METASK_AGENTCORE_STATUS_TOO_LATE: u32 = 5;
pub const METASK_AGENTCORE_STATUS_INVALID_STATE: u32 = 6;
pub const METASK_AGENTCORE_STATUS_CORE_ERROR: u32 = 7;
pub const METASK_AGENTCORE_STATUS_CALLBACK_FAILED: u32 = 8;
pub const METASK_AGENTCORE_STATUS_INTERNAL_ERROR: u32 = 9;
pub const METASK_AGENTCORE_STATUS_RESOURCE_LIMIT: u32 = 10;
pub const METASK_AGENTCORE_STATUS_SKILL_CATALOG_INVALID: u32 = 11;
pub const METASK_AGENTCORE_STATUS_STALE_CATALOG: u32 = 12;
pub const METASK_AGENTCORE_STATUS_SKILL_NOT_FOUND: u32 = 13;
pub const METASK_AGENTCORE_STATUS_INVALID_SKILL_ARGUMENTS: u32 = 14;
pub const METASK_AGENTCORE_STATUS_SKILL_POLICY_VIOLATION: u32 = 15;
pub const METASK_AGENTCORE_STATUS_SKILL_UNAVAILABLE: u32 = 16;
pub const METASK_AGENTCORE_STATUS_STALE_COMPACT: u32 = 17;
pub const METASK_AGENTCORE_PROVIDER_ANTHROPIC: u32 = 1;
pub const METASK_AGENTCORE_PROVIDER_OPENAI: u32 = 2;
pub const METASK_AGENTCORE_PROVIDER_GEMINI: u32 = 3;
pub const METASK_AGENTCORE_PERMISSION_DEFAULT: u32 = 1;
pub const METASK_AGENTCORE_PERMISSION_ACCEPT_EDITS: u32 = 2;
pub const METASK_AGENTCORE_PERMISSION_AUTO: u32 = 3;
pub const METASK_AGENTCORE_PERMISSION_DONT_ASK: u32 = 4;
pub const METASK_AGENTCORE_PERMISSION_BYPASS: u32 = 5;
pub const METASK_AGENTCORE_SHELL_DISABLED: u32 = 1;
pub const METASK_AGENTCORE_SHELL_SANDBOXED: u32 = 2;
pub const METASK_AGENTCORE_SHELL_UNRESTRICTED: u32 = 3;
pub const METASK_AGENTCORE_ABORT_USER_REQUEST: u32 = 1;
pub const METASK_AGENTCORE_ABORT_TIMEOUT: u32 = 2;
pub const METASK_AGENTCORE_STOP_END_TURN: u32 = 1;
pub const METASK_AGENTCORE_STOP_MAX_TURNS: u32 = 2;
pub const METASK_AGENTCORE_STOP_ABORTED: u32 = 3;
pub const METASK_AGENTCORE_STOP_TOOL_ERROR: u32 = 4;
pub const METASK_AGENTCORE_STOP_API_ERROR: u32 = 5;
pub const METASK_AGENTCORE_STOP_TOOL_LOOP: u32 = 6;
pub const METASK_AGENTCORE_MAX_TOOL_COUNT_V1: u32 = 1024;
pub const METASK_AGENTCORE_MAX_TOOL_SCHEMA_BYTES_V1: u32 = 1048576;
pub const METASK_AGENTCORE_MAX_TOOL_SCHEMA_DEPTH_V1: u32 = 32;
pub const METASK_AGENTCORE_MAX_TOOL_SCHEMA_PROPERTIES_V1: u32 = 1024;
pub const METASK_AGENTCORE_MAX_UI_RESPONSE_BYTES_V1: u32 = 1048576;
pub const METASK_AGENTCORE_MAX_HOST_TOOL_RESULT_BYTES_V1: u32 = 16777216;
pub const METASK_AGENTCORE_MAX_TOOL_ERROR_PAYLOAD_BYTES_V1: u32 = 1048576;
pub const METASK_AGENTCORE_MAX_SESSION_ID_BYTES_V1: u32 = 64;
pub const METASK_AGENTCORE_MAX_METADATA_STRING_BYTES_V1: u32 = 1048576;
pub const METASK_AGENTCORE_MAX_RUNTIME_METADATA_BYTES_V1: u32 = 16777216;
pub const METASK_AGENTCORE_MAX_SESSION_METADATA_BYTES_V1: u32 = 4194304;
pub const METASK_AGENTCORE_MAX_PROMPT_BYTES_V1: u32 = 16777216;
pub const METASK_AGENTCORE_MAX_SKILL_CATALOG_SKILLS_V1: u32 = 1024;
pub const METASK_AGENTCORE_MAX_SKILL_ARGUMENT_VALUES_V1: u32 = 64;
pub const METASK_AGENTCORE_MAX_SKILL_ARGUMENT_JSON_BYTES_V1: u32 = 1048576;
pub const METASK_AGENTCORE_MAX_PERMISSION_RULES_V1: u32 = 1024;
pub const METASK_AGENTCORE_MAX_PERMISSION_RULE_BYTES_V1: u32 = 65536;
pub const METASK_AGENTCORE_MAX_PERMISSION_RULE_TOTAL_BYTES_V1: u32 = 1048576;
pub const METASK_AGENTCORE_MAX_TURNS_V1: u32 = 1000;
pub const METASK_AGENTCORE_RUN_INPUT_TEXT: u32 = 1;
pub const METASK_AGENTCORE_RUN_INPUT_SKILL: u32 = 2;
pub const METASK_AGENTCORE_SKILL_SELECTION_DISABLED: u32 = 1;
pub const METASK_AGENTCORE_SKILL_SELECTION_ENABLED: u32 = 2;
pub const METASK_AGENTCORE_COMPACT_COMPACTED: u32 = 1;
pub const METASK_AGENTCORE_COMPACT_NO_CHANGE: u32 = 2;
pub const METASK_AGENTCORE_COMPACT_DEGRADED: u32 = 3;
pub const METASK_AGENTCORE_COMPACT_ABORTED: u32 = 4;
pub const METASK_AGENTCORE_EVENT_CONTINUE: u32 = 0;
pub const METASK_AGENTCORE_EVENT_FATAL: u32 = 1;
pub const METASK_AGENTCORE_UI_ANSWERED: u32 = 0;
pub const METASK_AGENTCORE_UI_UNAVAILABLE: u32 = 1;
pub const METASK_AGENTCORE_UI_FATAL: u32 = 2;
pub const METASK_AGENTCORE_UI_CANCELLED: u32 = 3;
pub const METASK_AGENTCORE_HOST_OK: u32 = 0;
pub const METASK_AGENTCORE_HOST_FAILED: u32 = 1;
pub const METASK_AGENTCORE_HOST_REJECTED: u32 = 2;
pub const METASK_AGENTCORE_HOST_FATAL: u32 = 3;
pub const METASK_AGENTCORE_CAP_RUNTIME: u32 = 1;
pub const METASK_AGENTCORE_CAP_BUILTIN_TOOLS: u32 = 2;
pub const METASK_AGENTCORE_CAP_HOST_SYNC_TOOLS: u32 = 4;
pub const METASK_AGENTCORE_CAP_HOST_UI: u32 = 8;
pub const METASK_AGENTCORE_CAP_CORE_EVENTS_JSON: u32 = 16;
pub const METASK_AGENTCORE_CAP_ABORT: u32 = 32;
pub const METASK_AGENTCORE_CAP_SKILL_CATALOG: u32 = 64;
pub const METASK_AGENTCORE_CAP_TYPED_RUN_INPUT: u32 = 128;
pub const METASK_AGENTCORE_CAP_SESSION_MODEL_MUTATION: u32 = 256;
pub const METASK_AGENTCORE_CAP_MANUAL_COMPACT: u32 = 512;
pub const METASK_AGENTCORE_CAP_SKILL_SELECTION: u32 = 1024;
pub const METASK_AGENTCORE_CAP_HOST_PERMISSION_RULES: u32 = 2048;
pub const METASK_AGENTCORE_REQUIRED_CAPABILITIES_V1: u32 = 4095;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_runtime {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_session {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_skill_catalog {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_bytes_view_v1 {
    pub ptr: *const u8,
    pub len: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_bytes_view_v1"]
        [::std::mem::size_of::<metask_agentcore_bytes_view_v1>() - 16usize];
    ["Alignment of metask_agentcore_bytes_view_v1"]
        [::std::mem::align_of::<metask_agentcore_bytes_view_v1>() - 8usize];
    ["Offset of field: metask_agentcore_bytes_view_v1::ptr"]
        [::std::mem::offset_of!(metask_agentcore_bytes_view_v1, ptr) - 0usize];
    ["Offset of field: metask_agentcore_bytes_view_v1::len"]
        [::std::mem::offset_of!(metask_agentcore_bytes_view_v1, len) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_owned_bytes_v1 {
    pub ptr: *mut u8,
    pub len: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_owned_bytes_v1"]
        [::std::mem::size_of::<metask_agentcore_owned_bytes_v1>() - 16usize];
    ["Alignment of metask_agentcore_owned_bytes_v1"]
        [::std::mem::align_of::<metask_agentcore_owned_bytes_v1>() - 8usize];
    ["Offset of field: metask_agentcore_owned_bytes_v1::ptr"]
        [::std::mem::offset_of!(metask_agentcore_owned_bytes_v1, ptr) - 0usize];
    ["Offset of field: metask_agentcore_owned_bytes_v1::len"]
        [::std::mem::offset_of!(metask_agentcore_owned_bytes_v1, len) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_run_context_v1 {
    pub struct_size: u32,
    pub reserved0: u32,
    pub session: *mut metask_agentcore_session,
    pub run_id: u64,
    pub session_id: metask_agentcore_bytes_view_v1,
    pub reserved: [u64; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_run_context_v1"]
        [::std::mem::size_of::<metask_agentcore_run_context_v1>() - 56usize];
    ["Alignment of metask_agentcore_run_context_v1"]
        [::std::mem::align_of::<metask_agentcore_run_context_v1>() - 8usize];
    ["Offset of field: metask_agentcore_run_context_v1::struct_size"]
        [::std::mem::offset_of!(metask_agentcore_run_context_v1, struct_size) - 0usize];
    ["Offset of field: metask_agentcore_run_context_v1::reserved0"]
        [::std::mem::offset_of!(metask_agentcore_run_context_v1, reserved0) - 4usize];
    ["Offset of field: metask_agentcore_run_context_v1::session"]
        [::std::mem::offset_of!(metask_agentcore_run_context_v1, session) - 8usize];
    ["Offset of field: metask_agentcore_run_context_v1::run_id"]
        [::std::mem::offset_of!(metask_agentcore_run_context_v1, run_id) - 16usize];
    ["Offset of field: metask_agentcore_run_context_v1::session_id"]
        [::std::mem::offset_of!(metask_agentcore_run_context_v1, session_id) - 24usize];
    ["Offset of field: metask_agentcore_run_context_v1::reserved"]
        [::std::mem::offset_of!(metask_agentcore_run_context_v1, reserved) - 40usize];
};
pub type metask_agentcore_host_execute_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        host_ctx: *mut ::std::os::raw::c_void,
        run: *const metask_agentcore_run_context_v1,
        arguments_json: metask_agentcore_bytes_view_v1,
        out_result: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_host_release_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        host_ctx: *mut ::std::os::raw::c_void,
        result: *mut metask_agentcore_owned_bytes_v1,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_host_tool_v1 {
    pub struct_size: u32,
    pub reserved0: u32,
    pub ctx: *mut ::std::os::raw::c_void,
    pub name: metask_agentcore_bytes_view_v1,
    pub description: metask_agentcore_bytes_view_v1,
    pub input_schema_json: metask_agentcore_bytes_view_v1,
    pub execute: metask_agentcore_host_execute_fn_v1,
    pub release_result: metask_agentcore_host_release_fn_v1,
    pub reserved: [u64; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_host_tool_v1"]
        [::std::mem::size_of::<metask_agentcore_host_tool_v1>() - 96usize];
    ["Alignment of metask_agentcore_host_tool_v1"]
        [::std::mem::align_of::<metask_agentcore_host_tool_v1>() - 8usize];
    ["Offset of field: metask_agentcore_host_tool_v1::struct_size"]
        [::std::mem::offset_of!(metask_agentcore_host_tool_v1, struct_size) - 0usize];
    ["Offset of field: metask_agentcore_host_tool_v1::reserved0"]
        [::std::mem::offset_of!(metask_agentcore_host_tool_v1, reserved0) - 4usize];
    ["Offset of field: metask_agentcore_host_tool_v1::ctx"]
        [::std::mem::offset_of!(metask_agentcore_host_tool_v1, ctx) - 8usize];
    ["Offset of field: metask_agentcore_host_tool_v1::name"]
        [::std::mem::offset_of!(metask_agentcore_host_tool_v1, name) - 16usize];
    ["Offset of field: metask_agentcore_host_tool_v1::description"]
        [::std::mem::offset_of!(metask_agentcore_host_tool_v1, description) - 32usize];
    ["Offset of field: metask_agentcore_host_tool_v1::input_schema_json"]
        [::std::mem::offset_of!(metask_agentcore_host_tool_v1, input_schema_json) - 48usize];
    ["Offset of field: metask_agentcore_host_tool_v1::execute"]
        [::std::mem::offset_of!(metask_agentcore_host_tool_v1, execute) - 64usize];
    ["Offset of field: metask_agentcore_host_tool_v1::release_result"]
        [::std::mem::offset_of!(metask_agentcore_host_tool_v1, release_result) - 72usize];
    ["Offset of field: metask_agentcore_host_tool_v1::reserved"]
        [::std::mem::offset_of!(metask_agentcore_host_tool_v1, reserved) - 80usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_runtime_config_v1 {
    pub struct_size: u32,
    pub reserved0: u32,
    pub builtin_tools: *const metask_agentcore_bytes_view_v1,
    pub builtin_tool_count: u64,
    pub host_tools: *const metask_agentcore_host_tool_v1,
    pub host_tool_count: u64,
    pub reserved: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_runtime_config_v1"]
        [::std::mem::size_of::<metask_agentcore_runtime_config_v1>() - 72usize];
    ["Alignment of metask_agentcore_runtime_config_v1"]
        [::std::mem::align_of::<metask_agentcore_runtime_config_v1>() - 8usize];
    ["Offset of field: metask_agentcore_runtime_config_v1::struct_size"]
        [::std::mem::offset_of!(metask_agentcore_runtime_config_v1, struct_size) - 0usize];
    ["Offset of field: metask_agentcore_runtime_config_v1::reserved0"]
        [::std::mem::offset_of!(metask_agentcore_runtime_config_v1, reserved0) - 4usize];
    ["Offset of field: metask_agentcore_runtime_config_v1::builtin_tools"]
        [::std::mem::offset_of!(metask_agentcore_runtime_config_v1, builtin_tools) - 8usize];
    ["Offset of field: metask_agentcore_runtime_config_v1::builtin_tool_count"]
        [::std::mem::offset_of!(metask_agentcore_runtime_config_v1, builtin_tool_count) - 16usize];
    ["Offset of field: metask_agentcore_runtime_config_v1::host_tools"]
        [::std::mem::offset_of!(metask_agentcore_runtime_config_v1, host_tools) - 24usize];
    ["Offset of field: metask_agentcore_runtime_config_v1::host_tool_count"]
        [::std::mem::offset_of!(metask_agentcore_runtime_config_v1, host_tool_count) - 32usize];
    ["Offset of field: metask_agentcore_runtime_config_v1::reserved"]
        [::std::mem::offset_of!(metask_agentcore_runtime_config_v1, reserved) - 40usize];
};
pub type metask_agentcore_on_event_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        session_ctx: *mut ::std::os::raw::c_void,
        run: *const metask_agentcore_run_context_v1,
        event_json: metask_agentcore_bytes_view_v1,
    ) -> u32,
>;
pub type metask_agentcore_on_ui_request_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        session_ctx: *mut ::std::os::raw::c_void,
        run: *const metask_agentcore_run_context_v1,
        request_json: metask_agentcore_bytes_view_v1,
        out_response: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_release_response_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        session_ctx: *mut ::std::os::raw::c_void,
        response: *mut metask_agentcore_owned_bytes_v1,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_session_callbacks_v1 {
    pub struct_size: u32,
    pub reserved0: u32,
    pub ctx: *mut ::std::os::raw::c_void,
    pub on_event: metask_agentcore_on_event_fn_v1,
    pub on_ui_request: metask_agentcore_on_ui_request_fn_v1,
    pub release_response: metask_agentcore_release_response_fn_v1,
    pub reserved: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_session_callbacks_v1"]
        [::std::mem::size_of::<metask_agentcore_session_callbacks_v1>() - 72usize];
    ["Alignment of metask_agentcore_session_callbacks_v1"]
        [::std::mem::align_of::<metask_agentcore_session_callbacks_v1>() - 8usize];
    ["Offset of field: metask_agentcore_session_callbacks_v1::struct_size"]
        [::std::mem::offset_of!(metask_agentcore_session_callbacks_v1, struct_size) - 0usize];
    ["Offset of field: metask_agentcore_session_callbacks_v1::reserved0"]
        [::std::mem::offset_of!(metask_agentcore_session_callbacks_v1, reserved0) - 4usize];
    ["Offset of field: metask_agentcore_session_callbacks_v1::ctx"]
        [::std::mem::offset_of!(metask_agentcore_session_callbacks_v1, ctx) - 8usize];
    ["Offset of field: metask_agentcore_session_callbacks_v1::on_event"]
        [::std::mem::offset_of!(metask_agentcore_session_callbacks_v1, on_event) - 16usize];
    ["Offset of field: metask_agentcore_session_callbacks_v1::on_ui_request"]
        [::std::mem::offset_of!(metask_agentcore_session_callbacks_v1, on_ui_request) - 24usize];
    ["Offset of field: metask_agentcore_session_callbacks_v1::release_response"]
        [::std::mem::offset_of!(metask_agentcore_session_callbacks_v1, release_response) - 32usize];
    ["Offset of field: metask_agentcore_session_callbacks_v1::reserved"]
        [::std::mem::offset_of!(metask_agentcore_session_callbacks_v1, reserved) - 40usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_skill_catalog_query_v1 {
    pub struct_size: u32,
    pub reserved0: u32,
    pub workspace_root: metask_agentcore_bytes_view_v1,
    pub workspace_home: metask_agentcore_bytes_view_v1,
    pub workspace_epoch: metask_agentcore_bytes_view_v1,
    pub reserved: [u64; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_skill_catalog_query_v1"]
        [::std::mem::size_of::<metask_agentcore_skill_catalog_query_v1>() - 80usize];
    ["Alignment of metask_agentcore_skill_catalog_query_v1"]
        [::std::mem::align_of::<metask_agentcore_skill_catalog_query_v1>() - 8usize];
    ["Offset of field: metask_agentcore_skill_catalog_query_v1::struct_size"]
        [::std::mem::offset_of!(metask_agentcore_skill_catalog_query_v1, struct_size) - 0usize];
    ["Offset of field: metask_agentcore_skill_catalog_query_v1::reserved0"]
        [::std::mem::offset_of!(metask_agentcore_skill_catalog_query_v1, reserved0) - 4usize];
    ["Offset of field: metask_agentcore_skill_catalog_query_v1::workspace_root"]
        [::std::mem::offset_of!(metask_agentcore_skill_catalog_query_v1, workspace_root) - 8usize];
    ["Offset of field: metask_agentcore_skill_catalog_query_v1::workspace_home"]
        [::std::mem::offset_of!(metask_agentcore_skill_catalog_query_v1, workspace_home) - 24usize];
    ["Offset of field: metask_agentcore_skill_catalog_query_v1::workspace_epoch"][::std::mem::offset_of!(
        metask_agentcore_skill_catalog_query_v1,
        workspace_epoch
    ) - 40usize];
    ["Offset of field: metask_agentcore_skill_catalog_query_v1::reserved"]
        [::std::mem::offset_of!(metask_agentcore_skill_catalog_query_v1, reserved) - 56usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_skill_selection_v1 {
    pub struct_size: u32,
    pub default_state_code: u32,
    pub exception_skill_ids: *const metask_agentcore_bytes_view_v1,
    pub exception_skill_id_count: u64,
    pub reserved: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_skill_selection_v1"]
        [::std::mem::size_of::<metask_agentcore_skill_selection_v1>() - 56usize];
    ["Alignment of metask_agentcore_skill_selection_v1"]
        [::std::mem::align_of::<metask_agentcore_skill_selection_v1>() - 8usize];
    ["Offset of field: metask_agentcore_skill_selection_v1::struct_size"]
        [::std::mem::offset_of!(metask_agentcore_skill_selection_v1, struct_size) - 0usize];
    ["Offset of field: metask_agentcore_skill_selection_v1::default_state_code"]
        [::std::mem::offset_of!(metask_agentcore_skill_selection_v1, default_state_code) - 4usize];
    ["Offset of field: metask_agentcore_skill_selection_v1::exception_skill_ids"]
        [::std::mem::offset_of!(metask_agentcore_skill_selection_v1, exception_skill_ids) - 8usize];
    ["Offset of field: metask_agentcore_skill_selection_v1::exception_skill_id_count"][::std::mem::offset_of!(
        metask_agentcore_skill_selection_v1,
        exception_skill_id_count
    ) - 16usize];
    ["Offset of field: metask_agentcore_skill_selection_v1::reserved"]
        [::std::mem::offset_of!(metask_agentcore_skill_selection_v1, reserved) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_permission_rule_set_v1 {
    pub struct_size: u32,
    pub reserved0: u32,
    pub allow: *const metask_agentcore_bytes_view_v1,
    pub allow_count: u64,
    pub ask: *const metask_agentcore_bytes_view_v1,
    pub ask_count: u64,
    pub deny: *const metask_agentcore_bytes_view_v1,
    pub deny_count: u64,
    pub reserved: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_permission_rule_set_v1"]
        [::std::mem::size_of::<metask_agentcore_permission_rule_set_v1>() - 88usize];
    ["Alignment of metask_agentcore_permission_rule_set_v1"]
        [::std::mem::align_of::<metask_agentcore_permission_rule_set_v1>() - 8usize];
    ["Offset of field: metask_agentcore_permission_rule_set_v1::struct_size"]
        [::std::mem::offset_of!(metask_agentcore_permission_rule_set_v1, struct_size) - 0usize];
    ["Offset of field: metask_agentcore_permission_rule_set_v1::reserved0"]
        [::std::mem::offset_of!(metask_agentcore_permission_rule_set_v1, reserved0) - 4usize];
    ["Offset of field: metask_agentcore_permission_rule_set_v1::allow"]
        [::std::mem::offset_of!(metask_agentcore_permission_rule_set_v1, allow) - 8usize];
    ["Offset of field: metask_agentcore_permission_rule_set_v1::allow_count"]
        [::std::mem::offset_of!(metask_agentcore_permission_rule_set_v1, allow_count) - 16usize];
    ["Offset of field: metask_agentcore_permission_rule_set_v1::ask"]
        [::std::mem::offset_of!(metask_agentcore_permission_rule_set_v1, ask) - 24usize];
    ["Offset of field: metask_agentcore_permission_rule_set_v1::ask_count"]
        [::std::mem::offset_of!(metask_agentcore_permission_rule_set_v1, ask_count) - 32usize];
    ["Offset of field: metask_agentcore_permission_rule_set_v1::deny"]
        [::std::mem::offset_of!(metask_agentcore_permission_rule_set_v1, deny) - 40usize];
    ["Offset of field: metask_agentcore_permission_rule_set_v1::deny_count"]
        [::std::mem::offset_of!(metask_agentcore_permission_rule_set_v1, deny_count) - 48usize];
    ["Offset of field: metask_agentcore_permission_rule_set_v1::reserved"]
        [::std::mem::offset_of!(metask_agentcore_permission_rule_set_v1, reserved) - 56usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_session_config_v1 {
    pub struct_size: u32,
    pub provider_kind_code: u32,
    pub permission_mode_code: u32,
    pub shell_policy_code: u32,
    pub api_key: metask_agentcore_bytes_view_v1,
    pub model: metask_agentcore_bytes_view_v1,
    pub base_url: metask_agentcore_bytes_view_v1,
    pub workspace_root: metask_agentcore_bytes_view_v1,
    pub workspace_home: metask_agentcore_bytes_view_v1,
    pub allowed_tools: *const metask_agentcore_bytes_view_v1,
    pub allowed_tool_count: u64,
    pub skill_catalog: *mut metask_agentcore_skill_catalog,
    pub skill_selection: *const metask_agentcore_skill_selection_v1,
    pub permission_rules: *const metask_agentcore_permission_rule_set_v1,
    pub reserved: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_session_config_v1"]
        [::std::mem::size_of::<metask_agentcore_session_config_v1>() - 168usize];
    ["Alignment of metask_agentcore_session_config_v1"]
        [::std::mem::align_of::<metask_agentcore_session_config_v1>() - 8usize];
    ["Offset of field: metask_agentcore_session_config_v1::struct_size"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, struct_size) - 0usize];
    ["Offset of field: metask_agentcore_session_config_v1::provider_kind_code"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, provider_kind_code) - 4usize];
    ["Offset of field: metask_agentcore_session_config_v1::permission_mode_code"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, permission_mode_code) - 8usize];
    ["Offset of field: metask_agentcore_session_config_v1::shell_policy_code"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, shell_policy_code) - 12usize];
    ["Offset of field: metask_agentcore_session_config_v1::api_key"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, api_key) - 16usize];
    ["Offset of field: metask_agentcore_session_config_v1::model"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, model) - 32usize];
    ["Offset of field: metask_agentcore_session_config_v1::base_url"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, base_url) - 48usize];
    ["Offset of field: metask_agentcore_session_config_v1::workspace_root"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, workspace_root) - 64usize];
    ["Offset of field: metask_agentcore_session_config_v1::workspace_home"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, workspace_home) - 80usize];
    ["Offset of field: metask_agentcore_session_config_v1::allowed_tools"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, allowed_tools) - 96usize];
    ["Offset of field: metask_agentcore_session_config_v1::allowed_tool_count"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, allowed_tool_count) - 104usize];
    ["Offset of field: metask_agentcore_session_config_v1::skill_catalog"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, skill_catalog) - 112usize];
    ["Offset of field: metask_agentcore_session_config_v1::skill_selection"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, skill_selection) - 120usize];
    ["Offset of field: metask_agentcore_session_config_v1::permission_rules"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, permission_rules) - 128usize];
    ["Offset of field: metask_agentcore_session_config_v1::reserved"]
        [::std::mem::offset_of!(metask_agentcore_session_config_v1, reserved) - 136usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_run_input_v1 {
    pub struct_size: u32,
    pub kind_code: u32,
    pub text: metask_agentcore_bytes_view_v1,
    pub skill_id: metask_agentcore_bytes_view_v1,
    pub catalog_revision: metask_agentcore_bytes_view_v1,
    pub arguments_json: metask_agentcore_bytes_view_v1,
    pub reserved: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_run_input_v1"]
        [::std::mem::size_of::<metask_agentcore_run_input_v1>() - 104usize];
    ["Alignment of metask_agentcore_run_input_v1"]
        [::std::mem::align_of::<metask_agentcore_run_input_v1>() - 8usize];
    ["Offset of field: metask_agentcore_run_input_v1::struct_size"]
        [::std::mem::offset_of!(metask_agentcore_run_input_v1, struct_size) - 0usize];
    ["Offset of field: metask_agentcore_run_input_v1::kind_code"]
        [::std::mem::offset_of!(metask_agentcore_run_input_v1, kind_code) - 4usize];
    ["Offset of field: metask_agentcore_run_input_v1::text"]
        [::std::mem::offset_of!(metask_agentcore_run_input_v1, text) - 8usize];
    ["Offset of field: metask_agentcore_run_input_v1::skill_id"]
        [::std::mem::offset_of!(metask_agentcore_run_input_v1, skill_id) - 24usize];
    ["Offset of field: metask_agentcore_run_input_v1::catalog_revision"]
        [::std::mem::offset_of!(metask_agentcore_run_input_v1, catalog_revision) - 40usize];
    ["Offset of field: metask_agentcore_run_input_v1::arguments_json"]
        [::std::mem::offset_of!(metask_agentcore_run_input_v1, arguments_json) - 56usize];
    ["Offset of field: metask_agentcore_run_input_v1::reserved"]
        [::std::mem::offset_of!(metask_agentcore_run_input_v1, reserved) - 72usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_run_options_v1 {
    pub struct_size: u32,
    pub max_turns: u32,
    pub reserved: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_run_options_v1"]
        [::std::mem::size_of::<metask_agentcore_run_options_v1>() - 40usize];
    ["Alignment of metask_agentcore_run_options_v1"]
        [::std::mem::align_of::<metask_agentcore_run_options_v1>() - 8usize];
    ["Offset of field: metask_agentcore_run_options_v1::struct_size"]
        [::std::mem::offset_of!(metask_agentcore_run_options_v1, struct_size) - 0usize];
    ["Offset of field: metask_agentcore_run_options_v1::max_turns"]
        [::std::mem::offset_of!(metask_agentcore_run_options_v1, max_turns) - 4usize];
    ["Offset of field: metask_agentcore_run_options_v1::reserved"]
        [::std::mem::offset_of!(metask_agentcore_run_options_v1, reserved) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_run_result_v1 {
    pub struct_size: u32,
    pub stop_reason_code: u32,
    pub turns: u32,
    pub tool_calls: u32,
    pub reserved: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_run_result_v1"]
        [::std::mem::size_of::<metask_agentcore_run_result_v1>() - 48usize];
    ["Alignment of metask_agentcore_run_result_v1"]
        [::std::mem::align_of::<metask_agentcore_run_result_v1>() - 8usize];
    ["Offset of field: metask_agentcore_run_result_v1::struct_size"]
        [::std::mem::offset_of!(metask_agentcore_run_result_v1, struct_size) - 0usize];
    ["Offset of field: metask_agentcore_run_result_v1::stop_reason_code"]
        [::std::mem::offset_of!(metask_agentcore_run_result_v1, stop_reason_code) - 4usize];
    ["Offset of field: metask_agentcore_run_result_v1::turns"]
        [::std::mem::offset_of!(metask_agentcore_run_result_v1, turns) - 8usize];
    ["Offset of field: metask_agentcore_run_result_v1::tool_calls"]
        [::std::mem::offset_of!(metask_agentcore_run_result_v1, tool_calls) - 12usize];
    ["Offset of field: metask_agentcore_run_result_v1::reserved"]
        [::std::mem::offset_of!(metask_agentcore_run_result_v1, reserved) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_compact_result_v1 {
    pub struct_size: u32,
    pub outcome_code: u32,
    pub before_context_tokens: u64,
    pub after_context_tokens: u64,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_read_input_tokens: u64,
    pub cache_creation_input_tokens: u64,
    pub reserved: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_compact_result_v1"]
        [::std::mem::size_of::<metask_agentcore_compact_result_v1>() - 88usize];
    ["Alignment of metask_agentcore_compact_result_v1"]
        [::std::mem::align_of::<metask_agentcore_compact_result_v1>() - 8usize];
    ["Offset of field: metask_agentcore_compact_result_v1::struct_size"]
        [::std::mem::offset_of!(metask_agentcore_compact_result_v1, struct_size) - 0usize];
    ["Offset of field: metask_agentcore_compact_result_v1::outcome_code"]
        [::std::mem::offset_of!(metask_agentcore_compact_result_v1, outcome_code) - 4usize];
    ["Offset of field: metask_agentcore_compact_result_v1::before_context_tokens"][::std::mem::offset_of!(
        metask_agentcore_compact_result_v1,
        before_context_tokens
    ) - 8usize];
    ["Offset of field: metask_agentcore_compact_result_v1::after_context_tokens"][::std::mem::offset_of!(
        metask_agentcore_compact_result_v1,
        after_context_tokens
    ) - 16usize];
    ["Offset of field: metask_agentcore_compact_result_v1::input_tokens"]
        [::std::mem::offset_of!(metask_agentcore_compact_result_v1, input_tokens) - 24usize];
    ["Offset of field: metask_agentcore_compact_result_v1::output_tokens"]
        [::std::mem::offset_of!(metask_agentcore_compact_result_v1, output_tokens) - 32usize];
    ["Offset of field: metask_agentcore_compact_result_v1::cache_read_input_tokens"][::std::mem::offset_of!(
        metask_agentcore_compact_result_v1,
        cache_read_input_tokens
    ) - 40usize];
    ["Offset of field: metask_agentcore_compact_result_v1::cache_creation_input_tokens"][::std::mem::offset_of!(
        metask_agentcore_compact_result_v1,
        cache_creation_input_tokens
    )
        - 48usize];
    ["Offset of field: metask_agentcore_compact_result_v1::reserved"]
        [::std::mem::offset_of!(metask_agentcore_compact_result_v1, reserved) - 56usize];
};
pub type metask_agentcore_runtime_create_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *const metask_agentcore_runtime_config_v1,
        arg2: *mut *mut metask_agentcore_runtime,
        arg3: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_runtime_destroy_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut metask_agentcore_runtime,
        arg2: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_runtime_query_skill_catalog_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut metask_agentcore_runtime,
        arg2: *const metask_agentcore_skill_catalog_query_v1,
        arg3: *mut *mut metask_agentcore_skill_catalog,
        arg4: *mut metask_agentcore_owned_bytes_v1,
        arg5: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_skill_catalog_release_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut metask_agentcore_skill_catalog,
        arg2: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_session_create_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut metask_agentcore_runtime,
        arg2: *const metask_agentcore_session_config_v1,
        arg3: *const metask_agentcore_session_callbacks_v1,
        arg4: *mut *mut metask_agentcore_session,
        arg5: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_session_destroy_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut metask_agentcore_session,
        arg2: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_session_set_model_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut metask_agentcore_session,
        arg2: metask_agentcore_bytes_view_v1,
        arg3: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_session_update_skills_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut metask_agentcore_session,
        optional_catalog: *mut metask_agentcore_skill_catalog,
        arg2: *const metask_agentcore_skill_selection_v1,
        arg3: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_session_update_permission_rules_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut metask_agentcore_session,
        arg2: *const metask_agentcore_permission_rule_set_v1,
        arg3: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_session_run_input_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        session: *mut metask_agentcore_session,
        run_id: u64,
        input: *const metask_agentcore_run_input_v1,
        options: *const metask_agentcore_run_options_v1,
        out_result: *mut metask_agentcore_run_result_v1,
        out_diagnostic: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_session_abort_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        session: *mut metask_agentcore_session,
        run_id: u64,
        reason_code: u32,
        out_diagnostic: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_session_compact_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        session: *mut metask_agentcore_session,
        operation_id: u64,
        out_result: *mut metask_agentcore_compact_result_v1,
        out_diagnostic: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_session_abort_compact_fn_v1 = ::std::option::Option<
    unsafe extern "C" fn(
        session: *mut metask_agentcore_session,
        operation_id: u64,
        out_diagnostic: *mut metask_agentcore_owned_bytes_v1,
    ) -> u32,
>;
pub type metask_agentcore_buffer_release_fn_v1 =
    ::std::option::Option<unsafe extern "C" fn(arg1: *mut metask_agentcore_owned_bytes_v1)>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct metask_agentcore_api_v1 {
    pub struct_size: u32,
    pub abi_version: u32,
    pub abi_revision: u32,
    pub reserved0: u32,
    pub capabilities: u64,
    pub runtime_create: metask_agentcore_runtime_create_fn_v1,
    pub runtime_destroy: metask_agentcore_runtime_destroy_fn_v1,
    pub runtime_query_skill_catalog: metask_agentcore_runtime_query_skill_catalog_fn_v1,
    pub skill_catalog_release: metask_agentcore_skill_catalog_release_fn_v1,
    pub session_create: metask_agentcore_session_create_fn_v1,
    pub session_destroy: metask_agentcore_session_destroy_fn_v1,
    pub session_set_model: metask_agentcore_session_set_model_fn_v1,
    pub session_update_skills: metask_agentcore_session_update_skills_fn_v1,
    pub session_update_permission_rules: metask_agentcore_session_update_permission_rules_fn_v1,
    pub session_run_input: metask_agentcore_session_run_input_fn_v1,
    pub session_abort: metask_agentcore_session_abort_fn_v1,
    pub session_compact: metask_agentcore_session_compact_fn_v1,
    pub session_abort_compact: metask_agentcore_session_abort_compact_fn_v1,
    pub buffer_release: metask_agentcore_buffer_release_fn_v1,
    pub reserved: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of metask_agentcore_api_v1"]
        [::std::mem::size_of::<metask_agentcore_api_v1>() - 168usize];
    ["Alignment of metask_agentcore_api_v1"]
        [::std::mem::align_of::<metask_agentcore_api_v1>() - 8usize];
    ["Offset of field: metask_agentcore_api_v1::struct_size"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, struct_size) - 0usize];
    ["Offset of field: metask_agentcore_api_v1::abi_version"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, abi_version) - 4usize];
    ["Offset of field: metask_agentcore_api_v1::abi_revision"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, abi_revision) - 8usize];
    ["Offset of field: metask_agentcore_api_v1::reserved0"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, reserved0) - 12usize];
    ["Offset of field: metask_agentcore_api_v1::capabilities"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, capabilities) - 16usize];
    ["Offset of field: metask_agentcore_api_v1::runtime_create"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, runtime_create) - 24usize];
    ["Offset of field: metask_agentcore_api_v1::runtime_destroy"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, runtime_destroy) - 32usize];
    ["Offset of field: metask_agentcore_api_v1::runtime_query_skill_catalog"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, runtime_query_skill_catalog) - 40usize];
    ["Offset of field: metask_agentcore_api_v1::skill_catalog_release"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, skill_catalog_release) - 48usize];
    ["Offset of field: metask_agentcore_api_v1::session_create"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, session_create) - 56usize];
    ["Offset of field: metask_agentcore_api_v1::session_destroy"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, session_destroy) - 64usize];
    ["Offset of field: metask_agentcore_api_v1::session_set_model"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, session_set_model) - 72usize];
    ["Offset of field: metask_agentcore_api_v1::session_update_skills"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, session_update_skills) - 80usize];
    ["Offset of field: metask_agentcore_api_v1::session_update_permission_rules"][::std::mem::offset_of!(
        metask_agentcore_api_v1,
        session_update_permission_rules
    ) - 88usize];
    ["Offset of field: metask_agentcore_api_v1::session_run_input"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, session_run_input) - 96usize];
    ["Offset of field: metask_agentcore_api_v1::session_abort"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, session_abort) - 104usize];
    ["Offset of field: metask_agentcore_api_v1::session_compact"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, session_compact) - 112usize];
    ["Offset of field: metask_agentcore_api_v1::session_abort_compact"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, session_abort_compact) - 120usize];
    ["Offset of field: metask_agentcore_api_v1::buffer_release"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, buffer_release) - 128usize];
    ["Offset of field: metask_agentcore_api_v1::reserved"]
        [::std::mem::offset_of!(metask_agentcore_api_v1, reserved) - 136usize];
};
unsafe extern "C" {
    pub fn metask_agentcore_get_api(requested_abi: u32) -> *const ::std::os::raw::c_void;
}
