import MetaCodesControl.ProjectHarness
import MetaCodesControl.RuleImpactGovernance

#print axioms MetaCodesControl.ProjectHarness.safePromotion_sound
#print axioms MetaCodesControl.ProjectHarness.correction_promotion_requires_receipt
#print axioms MetaCodesControl.ProjectHarness.denied_all_predecision_blocks
#print axioms MetaCodesControl.ProjectHarness.denied_existing_file_predecision_blocks
#print axioms MetaCodesControl.ProjectRule.denied_observed_overwrite_selects_exact_edit_recovery
#print axioms MetaCodesControl.ProjectRule.nonregular_target_has_no_exact_edit_recovery
#print axioms MetaCodesControl.ProjectRule.exact_edit_recovery_pre_sound
#print axioms MetaCodesControl.ProjectRule.exact_edit_recovery_post_sound
#print axioms MetaCodesControl.ProjectRule.exact_edit_recovery_failed_mutation_sound
#print axioms MetaCodesControl.ProjectHarness.decideBatch_sound
#print axioms MetaCodesControl.RuleImpactGovernance.safeTransition_sound
#print axioms MetaCodesControl.RuleImpactGovernance.unauthenticated_evidence_cannot_transition
#print axioms MetaCodesControl.RuleImpactGovernance.duplicate_window_cannot_transition
#print axioms MetaCodesControl.RuleImpactGovernance.unmetered_cache_cannot_transition
