//! Named system-prompt sections (#184).
//!
//! The system prompt is an ordered set of sections, each with a stable id
//! (`metacodes:*` for the kernel's own), an order, a class that says what a
//! Host may later do with it, and a join mode. Rendering sorts by
//! `(order, id)` and joins with a blank line.
//!
//! The join modes reproduce the historical layout byte for byte: the fixed
//! kernel sections (`always`) contribute their separator even when empty, as
//! the old concatenation did (an empty `# Using your tools` left a doubled
//! blank line), while the optional ones (`when_nonempty`) appear only with
//! text.

const std = @import("std");

/// What a Host may do with a section once Session prompt profiles exist.
pub const Class = enum {
    /// Governance text: never replaced or removed.
    locked,
    /// May be replaced with non-empty text, never removed.
    replaceable,
    /// May be replaced or removed.
    removable,
    /// Generated by the kernel from Session facts; never changed by a Host.
    generated,
};

pub const Join = enum { always, when_nonempty };

pub const Origin = enum { kernel, host };

pub const Section = struct {
    id: []const u8,
    order: i64,
    class: Class,
    join: Join,
    origin: Origin = .kernel,
    text: []const u8,
};

pub const separator = "\n\n";

fn lessThan(_: void, a: Section, b: Section) bool {
    if (a.order != b.order) return a.order < b.order;
    return std.mem.order(u8, a.id, b.id) == .lt;
}

/// Sort `sections` in place by `(order, id)` and join them. Ids are unique,
/// so the order is total.
pub fn render(allocator: std.mem.Allocator, sections: []Section) ![]u8 {
    std.mem.sort(Section, sections, {}, lessThan);
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);
    var first = true;
    for (sections) |section| {
        if (section.join == .when_nonempty and section.text.len == 0) continue;
        if (!first) try out.appendSlice(allocator, separator);
        try out.appendSlice(allocator, section.text);
        first = false;
    }
    return out.toOwnedSlice(allocator);
}

const testing = std.testing;

test "render orders by order then id and honours both join modes" {
    var sections = [_]Section{
        .{ .id = "b", .order = 20, .class = .removable, .join = .when_nonempty, .text = "" },
        .{ .id = "c", .order = 30, .class = .locked, .join = .always, .text = "C" },
        .{ .id = "a2", .order = 10, .class = .locked, .join = .always, .text = "" },
        .{ .id = "a1", .order = 10, .class = .locked, .join = .always, .text = "A" },
        .{ .id = "d", .order = 40, .class = .generated, .join = .when_nonempty, .text = "D" },
    };
    const rendered = try render(testing.allocator, &sections);
    defer testing.allocator.free(rendered);
    // a1, then the empty fixed a2 still joined, b skipped, c, d.
    try testing.expectEqualStrings("A\n\n\n\nC\n\nD", rendered);
}
