/// Closed daemon-side durable mutation inventory. Keeping this policy outside
/// the stable CLI command façade prevents a service concern from widening the
/// embedded public API; request metadata cannot downgrade a listed command.
pub fn mutatesDurableState(command: anytype, args: []const []const u8) bool {
    if (command == .store_info) {
        for (args) |arg| if (@import("std").mem.eql(u8, arg, "--refresh-size")) return true;
        return false;
    }
    return switch (command) {
        .init,
        .rebuild_text,
        .backup,
        .restore,
        .upgrade,
        .migrate_store_v2,
        .schema_apply,
        .schema_reconcile,
        .schema_migrate,
        .import_metaknow_replay,
        .import_jsonl,
        .export_jsonl,
        .apply,
        .import_markdown,
        .export_markdown,
        .import_md_ast,
        .import_md_doc,
        .gc_md_orphans,
        .memory_migration_commit,
        .materialize_checkpoint,
        .memory_migration_rollback,
        .add_node,
        .ensure_node,
        .ensure_anchor,
        .update_node,
        .append_node_version,
        .set_property,
        .set_uint_property,
        .set_node_property,
        .set_edge_property,
        .govern_node,
        .delete_node,
        .agent_write,
        .add_edge,
        .delete_edge,
        .delete_edges,
        .reparent_contain,
        .task_claim,
        .task_release,
        .task_close,
        .task_event,
        .export_segment_bundle,
        .gc_segment_bundle,
        .bench,
        .bench_md_doc_edit,
        .maintain,
        .compact_edges,
        .compact_edge_segments,
        .maintain_edge_segments,
        .gc_edge_segments,
        .gc_node_text_runs,
        => true,
        .help,
        .version,
        .stats,
        .store_info,
        .schema_info,
        .schema_show,
        .schema_validate,
        .render_md_doc,
        .get,
        .get_node,
        .schema_scope,
        .node_versions,
        .node_latest,
        .list_kinds,
        .list_recent,
        .list_rels,
        .find,
        .search,
        .context_plan,
        .context_packet,
        .neighbors,
        .incoming,
        .path,
        .task_ready,
        .task_packet,
        .task_snapshot,
        .ontology_rule_snapshot,
        .memory_migration_capabilities,
        .memory_migration_snapshot,
        .memory_migration_post_state,
        .task_frontier,
        .task_ancestry,
        .task_metrics,
        .query,
        .query_explain,
        .governance,
        .segment_query,
        .segment_query_explain,
        => false,
    };
}

test "daemon mutation classification cannot be downgraded through aliases" {
    const cli = @import("../cli.zig");
    try @import("std").testing.expect(mutatesDurableState(try cli.parseCommand("remember"), &.{}));
    try @import("std").testing.expect(mutatesDurableState(try cli.parseCommand("relate"), &.{}));
    try @import("std").testing.expect(mutatesDurableState(try cli.parseCommand("task-close"), &.{}));
    try @import("std").testing.expect(!mutatesDurableState(try cli.parseCommand("search"), &.{}));
    try @import("std").testing.expect(!mutatesDurableState(try cli.parseCommand("store-info"), &.{}));
    try @import("std").testing.expect(mutatesDurableState(
        try cli.parseCommand("store-info"),
        &.{"--refresh-size"},
    ));
}
