//! Model-visible protocol for TinyKG-backed work. This is deliberately
//! separate from lexical recall: retrieval finds durable knowledge, while the
//! task protocol controls state transitions and evidence closure.

pub const SYSTEM_RULES =
    \\Persistent task control-plane algorithm:
    \\- Treat TinyKG as the workflow source of truth. TaskStore, transcript summaries, startup text and Markdown are projections/caches; refresh live state with TaskList.
    \\- ACTIVATE: when a user task has multiple phases, is likely to cross compaction/restart, or explicitly asks you to preserve state for later phases, create exactly one persistent lifecycle anchor with TaskCreate before finishing the first phase. Require its result to contain a `kg-*` id and `persisted: true`; an in-session fallback is not equivalent. Immediately claim that same id with TaskUpdate `status: in_progress`, then use it throughout the task. Do not create duplicate anchors on later phases or after compaction.
    \\- SELECT: choose only a `kg-*` leaf whose `kg_status` is `open`, `readiness` is `ready`, and `claimed_by` is absent. Never steal or work a task held by another identity.
    \\- CLAIM: before doing work, call TaskUpdate with `status: in_progress`. The host injects the lease identity; never invent one. A successful claim returns a bounded `task_packet`.
    \\- RECOVER: read the packet before acting. It carries the parent objective, dependencies, claim state, evidence links, truncation diagnostics and continuations. `KgTaskPacketUnavailable` makes claim fail closed and normally releases the new lease; refresh TaskList and retry. If TaskGet returns `task_packet_unavailable`, stop and retry TaskGet. A title or compact summary alone is insufficient.
    \\- EXPERIENCE: a successful claim, or TaskGet recovery of a claimed task, may also return an `experience_packet` built from verified completed tasks and their execution-grounded ontology edges. Inspect it before any work. It is one bounded exact lexical probe, not proof of completeness; preserve tentative/confirmed state, follow evidence ids when relevant, and verify current reality before reusing prior behavior.
    \\- LEXICAL EXPANSION: TinyKG has no vectors. If the exact experience packet is insufficient, before work actively infer 2-4 separate compact semantic variants from this task (synonym/paraphrase, Chinese/English alias, mechanism, symptom, desired outcome, or nearby implementation term) and declare them once in lexical-query-plan-v3. The host executes the fixed batch and deduplicates node ids; never combine the neighborhood into one keyword bag.
    \\- WORK: preserve the stable `kg-*` id through tools, compaction and resume. After compaction or process restart, run TaskList and TaskGet again instead of trusting old conversational state. A resumed session may receive its live packet automatically.
    \\- CLOSE: after verifying the final artifacts or other completion evidence, every claimed task must end with TaskUpdate `completed` plus a concise verified `conclusion`, or `failed` plus evidence explaining the terminal failure. Include actual `acts_on` / `uses` / `produces` when known. Never use `deleted` for a persistent task and never leave finished work claimed/open.
    \\- CONTINUE: after close, inspect the returned frontier; dependencies unlock only from `completed`, never from `failed`. Terminal tasks keep kind `task` and remain inspectable by the same id through TaskGet/task packet.
;
